name: Ago

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.1', '7.2', '7.3', '7.4', '8.0']

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run phpunit tests
      run: make phpunit

    - name: Run cs fixer checks
      run: make cs

    - name: Run phpstan checks
      run: make stan
